export const projects = [
  {
    id: "armd",
    number: "01",
    title: "ARMD",
    subtitle: "Le site d’un cabinet de conseil B2B.",
    category: "SITE INSTITUTIONNEL · PROJET CLIENT",
    url: "https://armdgroup.com",
    tags: ["Direction artistique", "Astro / TypeScript", "SEO technique"],
    description:
      "Site institutionnel bilingue, multi-pages, pour un cabinet d’intelligence économique et d’influence stratégique : positionnement, méthode, expertises, références et prises de parole.",
    proof:
      "Direction artistique, design des pages, développement Astro et GSAP, mise en ligne sur Vercel et suivi Google Analytics 4. Livré en six semaines.",
    note: "Projet client réalisé en 2026 avec Mad Makers.",
    client: true,
    features: ["Site bilingue", "Multi-pages", "SEO technique", "GA4"],
    image: "/media/armd.webp",
  },
  {
    id: "expelled",
    number: "02",
    title: "EXPELLED",
    subtitle: "Un jeu de cartes en ligne.",
    category: "JEU DE CARTES EN LIGNE",
    url: "https://directedbymaick.github.io",
    tags: ["Conception produit", "Développement web", "Illustration IA"],
    description:
      "Un jeu de cartes avec boosters, collection personnelle, espace utilisateur, monétisation et arène joueur contre IA.",
    proof:
      "Conception du produit, développement des fonctionnalités et création des illustrations avec des outils d’IA.",
    note: "Illustrations créées avec Midjourney et ChatGPT Images 2.",
    features: [
      "Boosters & tirages",
      "Collection personnelle",
      "Espace utilisateur",
      "Monétisation",
      "Arène contre IA",
    ],
    image: null,
  },
  {
    id: "frieren",
    number: "03",
    title: "Frieren",
    subtitle: "Un site consacré à Frieren.",
    category: "EXPÉRIENCE WEB IMMERSIVE",
    url: "https://frierenconcept.netlify.app",
    tags: ["Direction artistique", "Interactions", "Développement"],
    description:
      "Un concept de site autour de Beyond Journey’s End, avec animations au défilement, vidéo et navigation interactive.",
    proof:
      "Direction artistique, composition des pages et développement des interactions.",
    note: "Concept personnel non officiel. Aucun lien commercial avec les ayants droit.",
    features: [
      "Storytelling visuel",
      "Animations au défilement",
      "Interactions",
      "Vidéo intégrée",
    ],
    image: "/media/frieren-2026.webp",
  },
  {
    id: "riot",
    number: "04",
    title: "Riot MMO",
    subtitle: "Un concept web pour Riot MMO.",
    category: "CONCEPT WEB CINÉMATIQUE",
    url: "https://riot-mmo.mad-makers.fr",
    tags: ["Direction artistique", "Three.js / WebGL", "Motion"],
    description:
      "Un concept de site pour explorer Runeterra, ses régions et son univers à travers une carte 3D et une navigation immersive.",
    proof:
      "Direction artistique, conception de l’interface et développement des interactions avec Three.js / WebGL.",
    note: "Concept personnel non officiel. Projet indépendant de Riot Games.",
    features: [
      "Carte 3D",
      "Univers & régions",
      "Motion design",
      "Navigation immersive",
    ],
    image: "/media/riot-2026.webp",
  },
];
export const jobs = [
  {
    company: "Maickstream",
    logo: "maickstream",
    logoTone: "light",
    logoFiles: ["twitch.svg", "youtube.svg"],
    track: "a1",
    role: "Créateur de contenu",
    date: "2022 — aujourd’hui",
    start: 2022,
    end: 2026.77,
    meta: "Twitch & YouTube · activité personnelle, toujours en cours",
    summary: "Une grande partie de mon activité : produire, monter, publier.",
    details: [
      "Création de contenus pour Twitch et YouTube, en direct et en vidéo.",
      "Montage vidéo et motion design des contenus publiés.",
      "Image de marque de la chaîne : identité visuelle et supports.",
      "Environ 2 000 abonnés sur YouTube, jusqu’à 10–30 k vues sur certaines vidéos.",
    ],
    tags: ["Twitch", "YouTube", "Montage vidéo", "Image de marque"],
  },
  {
    company: "Mad Makers",
    logo: "madmakers",
    logoTone: "dark",
    role: "Web designer & marketing digital indépendant",
    date: "2025 — aujourd’hui",
    start: 2025.67,
    end: 2026.77,
    meta: "Freelance, en attendant le poste qui me correspond",
    summary: "Mettre mes compétences au service de clients, le temps de trouver le bon poste.",
    details: [
      "Création de sites sur mesure : direction artistique, design et développement.",
      "Premier projet client livré : le site institutionnel ARMD, en six semaines.",
      "Conception et lancement de mad-makers.fr, la vitrine de l’activité.",
      "Prospection automatisée : CRM et campagnes email sur mesure.",
    ],
    tags: ["Freelance", "Sites web", "Direction artistique", "IA"],
  },
  {
    company: "VINCI Construction",
    logo: "vinci",
    logoTone: "light",
    role: "Chargé de marketing digital",
    date: "2024 — 2025",
    start: 2024.67,
    end: 2025.67,
    meta: "Nanterre · Alternance, master 2e année · Hybride",
    summary: "Des contenus aux événements, faire circuler les idées.",
    details: [
      "Création d’articles, vidéos, infographies et supports de communication.",
      "Refonte et gestion de l’arborescence SharePoint.",
      "Organisation et coordination de webinaires, conférences et salons.",
      "Gestion de projets avec les équipes internes et les partenaires externes.",
    ],
    tags: ["SharePoint", "Communication", "Gestion de projet"],
  },
  {
    company: "BIM&CO",
    logo: "bim",
    logoTone: "light",
    role: "Expert Marketing Digital",
    date: "2023 — 2024",
    start: 2023.67,
    end: 2024.67,
    meta: "Alternance, master 1re année · Marketing & contenu",
    summary: "Relier campagnes, CRM et production de contenu.",
    details: [
      "Lancement et gestion de campagnes marketing avec HubSpot.",
      "Gestion du site et du back-office WordPress.",
      "Création de supports visuels et vidéos ; gestion du calendrier éditorial.",
    ],
    tags: ["HubSpot", "WordPress", "Contenu"],
  },
  {
    company: "Sud Toilettes Sèches",
    logo: "sts",
    logoTone: "light",
    role: "Créateur de contenu & Business developer",
    date: "2021 — 2022",
    start: 2021,
    end: 2022,
    meta: "Communication & développement commercial",
    summary: "Créer du contenu et développer la prospection.",
    details: [
      "Production de contenus visuels et vidéos, calendrier éditorial et community management.",
      "Prospection téléphonique et par email.",
      "Campagnes LinkedIn avec Waalaxy et Sales Navigator.",
    ],
    tags: ["Création", "Prospection", "LinkedIn"],
  },
  {
    company: "Ineoprod",
    logo: "ineoprod",
    logoTone: "dark",
    role: "Créateur de contenu & Business developer",
    date: "2020 — 2021",
    start: 2020,
    end: 2021,
    meta: "Communication & développement commercial",
    summary: "Associer créativité et développement commercial.",
    details: [
      "Création de supports visuels et vidéos ; community management.",
      "Prospection téléphonique et par email.",
      "Campagnes LinkedIn avec LinkHelper et Sales Navigator.",
    ],
    tags: ["Contenu", "Community management"],
  },
  {
    company: "E-commerce indépendant",
    logo: "ecommerce",
    logoTone: "light",
    logoFiles: ["shopify.svg"],
    role: "Cofondateur · Marketing & acquisition",
    date: "2019 — 2020",
    start: 2019,
    end: 2020,
    meta: "Projet indépendant, avec un associé",
    summary: "Lancer des marques en ligne, du produit jusqu’aux ventes.",
    details: [
      "Création de boutiques en ligne sur Shopify, pour plusieurs marques lancées dans l’année.",
      "Création et sélection de produits.",
      "Campagnes Facebook Ads : création de publicités, ciblage et pilotage.",
      "Suivi et optimisation de campagnes publicitaires.",
      "De nombreuses formations en e-commerce suivies en parallèle : un vrai bagage technique, à la base de la suite de mon parcours.",
    ],
    tags: ["Shopify", "Facebook Ads", "E-commerce", "Formations"],
  },
  {
    company: "Orange Business Services",
    logo: "orange",
    logoTone: "dark",
    role: "Gestionnaire de portefeuille",
    date: "2016 — 2019",
    start: 2016,
    end: 2019,
    meta: "Relation client & développement commercial",
    summary: "Comprendre les besoins, entretenir la relation.",
    details: [
      "Gestion multicanale d’un portefeuille de 10 clients, dont ECF et Fayat.",
      "Développement commercial auprès des comptes suivis.",
      "Organisation et réalisation de challenges internes.",
    ],
    tags: ["Relation client", "Commercial", "Coordination"],
  },
];
export const certs = [
  [
    "RNCP36129",
    "Chef de projet en intelligence artificielle",
    "Pilotage de projets et stratégie IA.",
  ],
  [
    "RNCP37827",
    "Développeur en intelligence artificielle",
    "Développement de solutions d’intelligence artificielle.",
  ],
  [
    "RS6891 · Certif’IAG",
    "Contenus multimédias & IA responsable",
    "Produire et réviser du contenu professionnel multimédia en utilisant les outils d’IA générative de façon responsable. Certifopac.",
  ],
  [
    "RS6776",
    "Création rédactionnelle & visuelle avec l’IA",
    "Certification de création de contenu rédactionnel et visuel par l’usage responsable de l’IA générative.",
  ],
];
export const education = [
  {
    id: "cesame",
    short: "Césame Sup",
    logoFile: "cesame.png",
    logoTone: "light",
    year: 2021,
    start: 2020.67,
    end: 2021.67,
    date: "2020 — 2021",
    title: "Stratégies Marketing Opérationnel",
    school: "Césame Sup",
    level: "Bachelor",
    code: "",
  },
  {
    id: "dsp",
    short: "Master · École DSP",
    logoFile: "dsp.svg",
    logoTone: "light",
    year: 2025,
    start: 2023.67,
    end: 2025.67,
    date: "2023 — 2025",
    title: "Manager de la Stratégie Marketing",
    school: "École DSP",
    level: "Bac+5 · Master ou équivalent, en alternance",
    code: "",
    note: "Deux années en alternance : BIM&CO (2023 — 2024), puis VINCI Construction (2024 — 2025).",
  },
  {
    id: "framer",
    logoFile: "framer.svg",
    logoTone: "dark",
    short: "Framer",
    year: 2026,
    at: 2026.04,
    date: "Janv. 2026",
    title: "Créer son premier site web no code avec Framer",
    school: "Product builder no-code",
    level: "Bloc de compétences",
    code: "RNCP39108BC02",
  },
];
export const skills = [
  {
    id: "marketing",
    label: "Marketing B2B",
    title: "Campagnes & coordination",
    text: "Campagnes CRM, LinkedIn et prospection, calendrier éditorial, webinaires, conférences et salons. Le lien entre les équipes internes et les partenaires.",
    tools: ["HubSpot", "LinkedIn", "Sales Navigator", "Waalaxy", "Facebook Ads", "Shopify", "SharePoint"],
  },
  {
    id: "contenus",
    label: "Contenus & vidéo",
    title: "Raconter le métier",
    text: "Articles, infographies, supports de communication, montage vidéo et motion design pour le web et les réseaux sociaux.",
    tools: ["After Effects", "Premiere Pro", "Suite Adobe", "Création éditoriale"],
  },
  {
    id: "web",
    label: "Web",
    title: "Sites qui convainquent",
    text: "Conception, design et développement de sites rapides, accessibles et bien référencés, du site institutionnel à l’expérience 3D.",
    tools: ["Figma", "Spline", "Astro", "Next.js", "GSAP", "Three.js / WebGL", "WordPress", "Framer", "Vercel"],
    extra: "SEO technique · Accessibilité WCAG 2.2 AA · Core Web Vitals",
  },
  {
    id: "ia",
    label: "IA & automatisation",
    title: "Produire plus, mieux",
    text: "Agents de développement, génération d’images et de vidéos, prospection automatisée avec un CRM et des campagnes email sur mesure.",
    tools: ["Claude Code", "Codex", "Antigravity", "Midjourney", "ChatGPT Images", "Grok Imagine"],
  },
];
export const links = {
  email: "rayan.mpondo@gmail.com",
  phone: "07 66 03 98 08",
  phoneHref: "tel:+33766039808",
  linkedin: "https://www.linkedin.com/in/rayan-m-3a8ba6145/",
  youtube: "https://www.youtube.com/@maickstream",
  instagram: "https://www.instagram.com/darthmaick/",
  twitch: "https://www.twitch.tv/maickstream",
  studio: "https://www.mad-makers.fr",
  cv: "/CV_Rayan_MPONDO.pdf",
};
