'use client';
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from 'react';
import { projects, jobs, certs } from './content';
import HeroCarousel from './hero-carousel';
import SocialBackground from './social-background';
const linkedin='https://www.linkedin.com/in/rayan-m-3a8ba6145/';
const youtube='https://www.youtube.com/@maickstream';
const instagram='https://www.instagram.com/darthmaick/';
export default function CV(){
 const [selected,setSelected]=useState(0);
 const [preview,setPreview]=useState<'site'|'video'|null>(null);
 const [copyStatus,setCopyStatus]=useState('Copier l’email');
 const [quiet,setQuiet]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 const feature=projects[selected];
 useEffect(()=>{
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const nodes=document.querySelectorAll<HTMLElement>('.reveal');
  nodes.forEach(n=>n.classList.add('awaiting'));
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('awaiting');observer.unobserve(e.target)}}),{threshold:.08});
  nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect();
 },[]);
 useEffect(()=>{if(preview){dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}}},[preview]);
 const close=()=>{dialog.current?.close();setPreview(null)};
 async function copyEmail(){try{await navigator.clipboard.writeText('rayan.mpondo@gmail.com');setCopyStatus('Email copié ✓')}catch{setCopyStatus('rayan.mpondo@gmail.com')}}
 function nextTab(e:React.KeyboardEvent<HTMLButtonElement>,i:number){const next=e.key==='ArrowRight'?(i+1)%3:e.key==='ArrowLeft'?(i+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(next!==null){e.preventDefault();setSelected(next);document.getElementById(`tab-${next}`)?.focus()}}
 return <div className={quiet?'site quiet':'site'}>
 <a className="skip" href="#contenu">Aller au contenu</a>
 <header className="nav"><a className="wordmark" href="#accueil" aria-label="Rayan Mpondo, accueil">rm<span>.</span></a><nav aria-label="Navigation principale"><a href="#projets">Créations</a><a href="#parcours">Parcours</a><a href="#expertises">Expertises</a></nav><a className="nav-contact" href="#contact">Échangeons ↗</a></header>
 <main id="contenu">
 <section className="hero" id="accueil" aria-labelledby="hero-title"><p className="eyebrow hero-identity"><img className="identity-portrait" src="/media/rayan-portrait.png" alt="" width="48" height="48"/><span className="status-dot"/> RAYAN MPONDO · MARKETING & CRÉATION DIGITALE</p><h1 id="hero-title">La stratégie, <em>en tête.</em><br/>La création, <em>au bout des doigts.</em></h1><p className="hero-lead">Je transforme les idées en contenus, les marques en expériences.<br/>Du marketing digital aux sites qu’on n’oublie pas.</p><div className="hero-actions"><a className="button accent" href="#projets">Explorer mes créations <span>↓</span></a><a className="button ghost" href="/CV_Rayan_MPONDO.pdf" download>Mon CV en une page ↗</a></div>
 <HeroCarousel quiet={quiet} onProject={setSelected}/><div className="hero-bottom"><span>MELUN · ÎLE-DE-FRANCE</span><span>STRATÉGIE × DESIGN × IA</span><button onClick={()=>setQuiet(!quiet)} aria-pressed={quiet}>{quiet?'ANIMATIONS DÉSACTIVÉES':'ANIMATIONS ACTIVÉES'} ◌</button></div></section>
 <section className="intro wrap section reveal"><div><p className="eyebrow">LE PROFIL, EN QUELQUES MOTS</p><h2>Une tête stratégique.<br/>Un esprit de maker.</h2></div><div className="intro-copy"><p>Le marketing m’a appris à comprendre un public. La création m’a donné les moyens de le toucher.</p><p>Je combine campagnes digitales, production de contenus et conception web. J’aime autant structurer un projet que lui donner une identité, puis le faire vivre à l’écran.</p><a className="text-link" href={linkedin} target="_blank" rel="noreferrer">Retrouvons-nous sur LinkedIn ↗</a></div></section>
 <section id="projets" className="projects section" aria-labelledby="projects-title"><div className="wrap"><div className="section-heading reveal"><div><p className="eyebrow">01 / LES PREUVES PAR LE FAIRE</p><h2 id="projects-title">Les idées prennent vie.</h2></div><p>Du site immersif au produit interactif.<br/>Une sélection de mes créations.</p></div>
 <div className="project-tabs" role="tablist" aria-label="Sélectionner un projet">{projects.map((p,i)=><button key={p.id} id={`tab-${i}`} role="tab" aria-controls="project-panel" aria-selected={selected===i} tabIndex={selected===i?0:-1} onKeyDown={e=>nextTab(e,i)} onClick={()=>setSelected(i)}><span>{p.number}</span>{p.title}<span aria-hidden="true">↗</span></button>)}</div>
 <article className="project-panel" id="project-panel" role="tabpanel" aria-labelledby={`tab-${selected}`} tabIndex={0}><div className={`project-visual ${feature.id}`} key={feature.id}>{feature.image?<img className="project-cover" src={feature.image} alt={`Aperçu du site ${feature.title}`} width="1875" height="968" loading="lazy"/>:<div className="game-art"><div className="game-label"><span>UN UNIVERS ORIGINAL</span><strong>EXPELLED</strong><span>NÉS DU SILENCE</span></div><div className="card-fan"><img src="/media/eshel.webp" alt="Eshel, illustration du jeu EXPELLED" width="640" height="900" loading="lazy"/><img src="/media/doran.webp" alt="Doran, illustration du jeu EXPELLED" width="640" height="900" loading="lazy"/><img src="/media/rasen.webp" alt="Rasen, illustration du jeu EXPELLED" width="640" height="900" loading="lazy"/></div><span className="art-caption">ILLUSTRATIONS DU JEU · CRÉATION ASSISTÉE PAR IA</span></div>}<div className="project-visual-bar"><span>{feature.category}</span><button onClick={()=>setPreview(feature.id==='frieren'?'video':'site')}>{feature.id==='frieren'?'Voir la démo vidéo':'Explorer dans la page'} ↗</button></div></div>
 <div className="project-description"><div><p className="eyebrow">{feature.title.toUpperCase()}</p><h3>{feature.subtitle}</h3><div className="tags">{feature.tags.map(t=><span key={t}>{t}</span>)}</div></div><div><p>{feature.description}</p><p className="project-proof">{feature.proof}</p><div className="feature-list">{feature.features.map(f=><span key={f}><i aria-hidden="true">＋</i>{f}</span>)}</div><a className="text-link" href={feature.url} target="_blank" rel="noreferrer">Ouvrir le projet ↗</a><p className="project-note">{feature.note}</p></div></div></article>
 <a className="studio-band" href="https://www.mad-makers.fr" target="_blank" rel="noreferrer"><div><span className="eyebrow">MON UNIVERS CRÉATIF</span><h3>Mad Makers<span>.</span></h3></div><p>Direction artistique, création web et expériences digitales.<br/>Retrouvez l’ensemble de mes projets.</p><span className="circle-arrow" aria-hidden="true">↗</span></a></div></section>
 <section className="content-section section wrap" id="contenus"><div className="section-heading reveal"><div><p className="eyebrow">02 / CRÉER, MONTER, PARTAGER</p><h2>Le sens du rythme.<br/>Le goût du contenu.</h2></div><p>Une pratique créative qui continue<br/>bien après les projets professionnels.</p></div><div className="creator-grid"><article className="youtube-card reveal"><SocialBackground kind="youtube" quiet={quiet}/><div className="social-heading"><span>YOUTUBE / @MAICKSTREAM</span><span>↗</span></div><div className="youtube-mark" aria-hidden="true">▶</div><h3>Créer pour être regardé.</h3><p>Du contenu vidéo, une communauté et l’envie de donner rendez-vous au prochain épisode.</p><div className="metrics"><div><strong>≈ 2 000</strong><span>abonnés</span></div><div><strong>10–30 k</strong><span>vues sur certaines vidéos</span></div></div><a className="social-cta" href={youtube} target="_blank" rel="noreferrer">Découvrir la chaîne <span>↗</span></a></article>
 <article className="amv-card reveal"><SocialBackground kind="instagram" quiet={quiet}/><div className="social-heading"><span>INSTAGRAM / AMV</span><span>↗</span></div><div className="amv-symbol" aria-hidden="true"><span>Ae</span><span>Pr</span></div><h3>L’émotion, image par image.</h3><p>Mes AMV explorent le montage, les effets et la synchronisation musicale avec Adobe After Effects et Premiere Pro.</p><a className="social-cta" href={instagram} target="_blank" rel="noreferrer">Voir les montages sur Instagram <span>↗</span></a></article></div><p className="metrics-note">Audience YouTube approximative, communiquée en août 2026.</p></section>
 <section id="parcours" className="experience section"><div className="wrap career-grid"><div className="career-heading reveal"><p className="eyebrow">03 / LE PARCOURS</p><h2>La créativité,<br/>sur le terrain.</h2><figure className="career-portrait"><img src="/media/rayan-portrait.png" alt="Portrait de Rayan Mpondo" width="1254" height="1254" loading="lazy"/><figcaption><span>Rayan Mpondo</span><span>MARKETING · CRÉATION · IA</span></figcaption></figure><p>De la relation client au marketing digital, un fil conducteur : comprendre, créer et coordonner.</p><a className="button ghost" href="/CV_Rayan_MPONDO.pdf" download>Télécharger mon CV ↓</a></div><div className="timeline">{jobs.map((job,i)=><details key={job.company} className="job reveal" open={i===0}><summary><span className="job-top"><span className={`job-logo ${job.logoTone}`}><img src={`/logos/${job.logo}.png`} alt="" width="120" height="56" loading="lazy"/></span><span className="job-date">{job.date}</span></span><span className="job-head"><span className="job-company">{job.company}</span><span className="expand" aria-hidden="true">＋</span></span><span className="job-role">{job.role}</span></summary><div className="job-detail"><p className="job-meta">{job.meta}</p><p className="job-summary">{job.summary}</p><ul>{job.details.map(d=><li key={d}>{d}</li>)}</ul><div className="tags">{job.tags.map(t=><span key={t}>{t}</span>)}</div></div></details>)}</div></div></section>
 <section id="expertises" className="section wrap"><div className="section-heading reveal"><div><p className="eyebrow">04 / CE QUE J’APPORTE</p><h2>Du fond. De la forme.<br/>Et le lien entre les deux.</h2></div></div><div className="skills-grid"><article className="skill reveal"><span className="skill-index">01 — STRATÉGIE</span><h3>Comprendre<br/>avant de créer.</h3><p>Campagnes marketing, CRM, relation client et coordination de projets. Des contenus pensés pour leur public.</p><div className="tool-list">HubSpot · SharePoint · LinkedIn<br/>Waalaxy · Sales Navigator</div></article><article className="skill reveal"><span className="skill-index">02 — CRÉATION</span><h3>Donner une forme<br/>aux idées.</h3><p>Direction artistique, vidéo, motion design, AMV et supports de communication. Une identité, jusque dans les détails.</p><div className="tool-list">After Effects · Premiere Pro<br/>Suite Adobe · Création éditoriale</div></article><article className="skill reveal"><span className="skill-index">03 — WEB & IA</span><h3>Construire<br/>et expérimenter.</h3><p>Sites immersifs, interfaces et expériences interactives. L’IA générative comme outil de production créative responsable.</p><div className="tool-list">Framer · WordPress · Three.js<br/>Midjourney · ChatGPT Images 2</div></article></div></section>
 <section className="learning section"><div className="wrap"><div className="section-heading reveal"><div><p className="eyebrow">05 / TOUJOURS EN APPRENTISSAGE</p><h2>Une base solide.<br/>Un regard vers la suite.</h2></div></div><div className="learning-grid"><div className="education"><h3>Formation</h3><article><span>2026</span><div><h4>Créer son premier site web no code avec Framer</h4><p>Product builder no-code<br/>RNCP39108BC02</p></div></article><article><span>2025</span><div><h4>Manager de la Stratégie Marketing</h4><p>École DSP · Bac+5<br/>Master ou équivalent</p></div></article><article><span>2020–21</span><div><h4>Stratégies Marketing Opérationnel</h4><p>Césame Sup · Bachelor</p></div></article></div><div className="certifications"><h3>Certifications en intelligence artificielle</h3>{certs.map(c=><details key={c[0]}><summary><span className="cert-code">{c[0]}</span><span>{c[1]}</span><b aria-hidden="true">＋</b></summary><p>{c[2]}</p></details>)}</div></div></div></section>
 <section id="contact" className="contact section wrap reveal"><img className="contact-portrait" src="/media/rayan-portrait.png" alt="Rayan Mpondo" width="88" height="88" loading="lazy"/><p className="eyebrow">LA SUITE S’ÉCRIT ENSEMBLE</p><h2>Et si on créait<br/><em>la suite ?</em></h2><p>Vous cherchez un profil qui relie marketing, création et digital ?<br/>Parlons de votre équipe et de vos projets.</p><div className="contact-actions"><a className="button accent" href="mailto:rayan.mpondo@gmail.com">Écrivez-moi ↗</a><button className="button ghost" onClick={copyEmail} aria-live="polite">{copyStatus}</button></div><a className="email-address" href="mailto:rayan.mpondo@gmail.com">rayan.mpondo@gmail.com</a><div className="contact-meta"><span>Melun · Île-de-France</span><a href="tel:+33766039808">07 66 03 98 08</a></div></section>
 </main><footer className="footer wrap"><a className="wordmark" href="#accueil" aria-label="Retour à l’accueil">rm<span>.</span></a><span>RAYAN MPONDO · 2026</span><div><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={youtube} target="_blank" rel="noreferrer">YouTube ↗</a><a href={instagram} target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.twitch.tv/maickstream" target="_blank" rel="noreferrer">Twitch ↗</a></div><a href="#accueil" className="back-top" aria-label="Retour en haut">↑</a></footer>
 <dialog ref={dialog} className="preview-dialog" aria-labelledby="preview-title" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}} onClose={()=>setPreview(null)}><div className="dialog-shell"><div className="dialog-heading"><div><span className="eyebrow">{preview==='video'?'DÉMONSTRATION ENREGISTRÉE':'SITE EXTERNE INTERACTIF'}</span><h2 id="preview-title">{feature.title}</h2></div><button className="close-preview" onClick={close} autoFocus aria-label="Fermer l’aperçu">×</button></div>{preview==='video'?<video src="/media/frieren-demo.mp4" controls playsInline preload="metadata" aria-label="Démonstration des interactions du site Frieren"/>:preview==='site'?<iframe key={feature.id} src={feature.url} title={`Site ${feature.title}`} referrerPolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox"/>:null}<div className="dialog-foot"><p>{preview==='video'?'Capture des interactions du projet Frieren.':'Le site peut limiter son affichage intégré. Ouvrez-le dans un nouvel onglet si nécessaire.'}</p><a className="text-link" href={feature.url} target="_blank" rel="noreferrer">Ouvrir le site ↗</a></div></div></dialog>
 </div>;
}


